// <auto-generated />
namespace LastChance.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _2plikExcel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_2plikExcel));
        
        string IMigrationMetadata.Id
        {
            get { return "201705121557343_2 plik Excel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
