// <auto-generated />
namespace LastChance.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class comments3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(comments3));
        
        string IMigrationMetadata.Id
        {
            get { return "201705211055010_comments3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
